#!/usr/bin/env -S deno run -A
// #region imports
import { Database, RestBindParameters } from "@db/sqlite";
import { parseArgs } from "@std/cli";
import { resolve } from "@std/path";
import { ensureDir, exists, copy } from "@std/fs";
// #endregion
// #region compositions
const tap = <T>(t: T, f: (t: T) => void) => { f(t); return t; };
const pipe = <T, R>(t: T, f: (t: T) => R) => { return f(t); };
const pose = <T extends unknown[], U extends unknown[], R>(f: (...u: U) => R, g: (...t: T) => U) => (...t: T) => f(...g(...t));
// #endregion
// #region sanity check
const ensureAllExist = async (dir: string, fs: string[]) => {
    for (const f of fs) if (!await exists(resolve(dir, f)))
        throw new Error(`expected file ${resolve(dir, f)} to exist, is missing`);
};
const src = import.meta.dirname;
if (!src) throw new Error(`failed to get import.meta.dirname`);
await ensureAllExist(src, ["wq", "PRIMER.md", "usage.txt", "validator.default", "schema.sql"]);
// #endregion
// #region help, init (commands that don't open an existing db)
const cmd = Deno.args.shift();
const help = async () => console.error(await Deno.readTextFile(resolve(src, "usage.txt")));
if (typeof cmd !== "string" || cmd === "help") { await help(); Deno.exit(); } else if (cmd === "init") {
    const wqd = resolve(Deno.cwd(), ".wq");
    await ensureDir(wqd);
    const db = new Database(resolve(wqd, "db"));
    db.exec("pragma journal_mode = WAL;");
    db.exec(await Deno.readTextFile(resolve(src, "schema.sql")));
    await copy(resolve(src, "validator.default"), resolve(wqd, "validator"));
    await Deno.chmod(resolve(wqd, "validator"), 0o775);
    console.error(`init: created ${wqd}`);
    Deno.exit();
}
// #endregion
// #region find .wq
const wqd = await (async () => {
    let d = Deno.cwd(); let p = d;
    do { const r = resolve(d = p, ".wq"); if (await exists(r)) return r; } while (d !== (p = resolve(d, "..")));
    throw new Error("coulnd't find .wq");
})();
ensureAllExist(wqd, ["db", "validator"]);
// #endregion
// #region types
type ItemId = number;
type ItemSummary = { id: ItemId, status: string, type: string, name: string };
type Item = ItemSummary & { description: string };
type Links = Record<string, ItemSummary[]>;
type ItemLinks = Item & { links: Links };
// #endregion
// #region db core
const issueFields = ["type", "status", "name", "description"] as const;
const conn = new Database(resolve(wqd, "db")); conn.exec("pragma foreign_keys = ON");
const binds = (f: string[], sep: string = ", ") => f.map(s => `${s} = ?`).join(sep);
const q = <TCols extends unknown[], TBind extends RestBindParameters, TRet = TCols> (query: string, f: (...t: TCols) => TRet) =>
    pipe(conn.prepare(query), stmt => (...bind: TBind) => stmt.values<TCols>(...bind).map(col => f(...col)));
const Q = <TCols extends unknown[], TBind extends RestBindParameters, TRet = TCols> (query: string, f: (...t: TCols) => TRet) =>
    pipe(conn.prepare(query), stmt => (...bind: TBind) => pipe(stmt.value<TCols>(...bind), ret => ret ? f(...ret) : undefined));
const E = <TBind extends RestBindParameters> (query: string) => pipe(conn.prepare(query), stmt => (...bind: TBind) => { stmt.run(...bind); });
// #endregion
// #region db statements
const db = {
    get: Q<[ItemId, string, string, string, string], [ItemId], Item>(
        "SELECT id, status, type, name, description FROM item WHERE id = ?",
        (id, status, type, name, description) => ({ id, status, type, name, description })),
    fwd: q<[string, ItemId, string, string, string], [ItemId], [string, ItemSummary]>(
        "SELECT link.type AS rel, item.id, item.status, item.type, item.name FROM link JOIN item ON item.id = link.b WHERE link.a = ?",
        (rel, id, status, type, name) => [rel, { id, status, type, name }]),
    bwd: q<[string, ItemId, string, string, string], [ItemId], [string, ItemSummary]>(
        `SELECT linktype.back AS rel, item.id, item.status, item.type, item.name FROM link
            JOIN linktype ON linktype.type = link.type JOIN item ON item.id = link.a WHERE link.b = ?`,
        (rel, id, status, type, name) => [rel, { id, status, type, name }]),
    cItem: Q<[ItemId], [string, string, string, string], ItemId>("INSERT INTO item (type, status, name, description) VALUES (?, ?, ?, ?) RETURNING id", (id) => id),
    cLink: E<[string, ItemId, ItemId]>("INSERT INTO link (type, a, b) VALUES (?, ?, ?)"),
    rLink: E<[string, ItemId, ItemId]>("DELETE FROM link WHERE type = ? AND a = ? AND b = ?")
} as const;
// #endregion
// #region db
const statuses = ["open", "claimed", "closed"]; // TODO: allow config-ing this
const itemTypes = q<[string], [], string>(`SELECT type FROM itemtype`, (t) => t)();
const linkTypes = q<[string, string], [], [string, string]>(`SELECT type, back FROM linktype`, (f,b) => [f,b])();
const backlinkTypes = Object.fromEntries(linkTypes.map((f,b) => [b,f]));
const normalizeLink = (t: string, a: number, b: number) => t in backlinkTypes ? [backlinkTypes[t], b, a] : [t, a, b];
const rels = (id: number) => pipe([...db.fwd(id), ...db.bwd(id)], raw => tap<Links>({}, res => {
    for (const [rel,r] of raw) (res[rel] ??= []).push(r);
}));
const show = (id: number): ItemLinks | undefined => pipe(db.get(id), res => res && ({ ...res, links: rels(id) }));
// #endregion
// #region main
const args = parseArgs(Deno.args, {
    boolean: ["human", "claim"], string: issueFields, alias: { "h": "human" },
    collect: linkTypes.flat() as ["blocks", "blocked-by"], // lie to the type system or it thinks everything is arrays
});
const idArgs = () => {
    args._.filter(it => typeof it !== "number").forEach(it => console.error(`warn: ${it} is not a valid item id`));
    return args._.filter(it => typeof it === "number");
};
const requireDef = <T>(t: T, msg: string): NonNullable<T> => { if (t === undefined) throw new Error(msg); return t!; }
const requireArg = <T extends keyof typeof args>(arg: T) => requireDef(args[arg], `argument ${arg} is required`);
const J = (x: unknown) => console.log(JSON.stringify(x)); // TODO: --human
const cmds = {
    "prime": async () => {
        const parts: Record<string, string> = {
            itemTypes: itemTypes.join("|"), statuses: statuses.join("|"),
            linkArgs: linkTypes.map(([a,b]) => `--${a} <id> --${b} <id>`).join("  "),
            wqSrc: resolve(src, "wq"),
        };
        console.log(await Deno.readTextFile(resolve(src, "PRIMER.md"))
            .then(it => it.replaceAll(/\{([^\}]+)\}/g, (_,k) => parts[k])));
    },
    "show": () => J(idArgs().map(id => show(id) || console.error(`warn: item ${id} does not exist`)).filter(it => it)),
    "create": () => J(show(db.cItem(requireArg("type"), args.status || "open", requireArg("name"), requireArg("description"))!)),
    "update": () => pipe(pipe(issueFields.filter(k => args[k]), fields => pipe(E(`UPDATE item SET ${binds(fields)} WHERE id = ?`), stmt =>
        pipe(fields.map(k => args[k]), vals => pose<[number], RestBindParameters, void>(stmt, id => [...vals, id])))), doUpdate =>
            J(idArgs().map(id => { doUpdate(id); return show(id); }))),
    "link": () => { console.error("not yet implemented") },
    "unlink": () => { console.error("not yet implemented") },
    "list": () => { console.error("not yet implemented") },
    "ready": () => { console.error("not yet implemented") },
    "blocked": () => { console.error("not yet implemented") },
    "claim": () => { console.error("not yet implemented") },
    "unclaim": () => { console.error("not yet implemented") },
    "close": () => { console.error("not yet implemented") },
};
if (cmd in cmds) await cmds[cmd as keyof typeof cmds](); else await help();
// #endregion
