#!/usr/bin/env -S deno run -A
// #region imports
import { Database, type RestBindParameters } from "@db/sqlite";
import { parseArgs } from "@std/cli";
import { resolve } from "@std/path";
import { ensureDir, exists, copy } from "@std/fs";
// #endregion
// #region compositions
const tap = <T>(t: T, f: (t: T) => void) => { f(t); return t; };
const pipe = <T, R>(t: T, f: (t: NonNullable<T>) => R): T extends undefined ? R | undefined : R => t === undefined ? undefined! : f(t!);
// #endregion
// #region help, init (commands that don't open an existing db)
const aliases: Record<string, string> = {"view": "show", "add": "create", "edit": "update", "modify": "update"};
const cmd = pipe(Deno.args.shift(), it => it && it in aliases ? aliases[it] : it);
const src = import.meta.dirname; if (!src) err(`failed to get import.meta.dirname`);
const help = () => console.error(Deno.readTextFileSync(resolve(src!, "usage.txt")));
function err(msg: string, printUsage: boolean = false): never { console.error("err: " + msg); if (printUsage) help(); Deno.exit(1); }
const ensureAllExist = async (dir: string, fs: string[]) => {
    for (const f of fs) if (!await exists(resolve(dir, f)))
        err(`expected file ${resolve(dir, f)} to exist, is missing`);
};
await ensureAllExist(src, ["wq", "PRIMER.md", "usage.txt", "validator.default", "schema.sql"]);
if (typeof cmd !== "string" || cmd === "help") { help(); Deno.exit(); } else if (cmd === "init") {
    const wqd = resolve(Deno.cwd(), ".wq");
    await ensureDir(wqd);
    const db = new Database(resolve(wqd, "db"));
    db.exec("pragma journal_mode = WAL;");
    db.exec(await Deno.readTextFile(resolve(src, "schema.sql")));
    await copy(resolve(src, "validator.default"), resolve(wqd, "validator"));
    await Deno.chmod(resolve(wqd, "validator"), 0o775);
    await copy(resolve(src, "config.default.json"), resolve(wqd, "config.json"));
    console.error(`init: created ${wqd}`);
    Deno.exit();
}
// #endregion
// #region find .wq
const wqd = await (async () => {
    let d = Deno.cwd(); let p = d;
    do { const r = resolve(d = p, ".wq"); if (await exists(r)) return r; } while (d !== (p = resolve(d, "..")));
    err("coulnd't find .wq");
})();
await ensureAllExist(wqd, ["db", "validator", "config.json"]);
// #endregion
// #region types
type ItemId = number;
type ItemSummary = { id: ItemId, status: string, type: string, name: string };
type Item = ItemSummary & { description: string };
type Links = Record<string, ItemSummary[]>;
type ItemLinks = Item & { links: Links };
type SingleOrArray<T> = T | T[];
type Output = SingleOrArray<ItemSummary | ItemLinks>;
// #endregion
// #region db core
const issueFields = ["type", "status", "name", "description"] as const;
const conn = new Database(resolve(wqd, "db")); conn.exec("pragma foreign_keys = ON");
const q = <TCols extends unknown[], TBind extends RestBindParameters, TRet = TCols> (f: (...t: TCols) => TRet, query: string) =>
    pipe(conn.prepare(query), stmt => (...bind: TBind) => stmt.values<TCols>(...bind).map(col => f(...col)));
const Q = <TCols extends unknown[], TBind extends RestBindParameters, TRet = TCols> (f: (...t: TCols) => TRet, query: string) =>
    pipe(conn.prepare(query), stmt => (...bind: TBind) => pipe(stmt.value<TCols>(...bind), ret => ret ? f(...ret) : undefined));
const E = <TBind extends RestBindParameters> (query: string) => pipe(conn.prepare(query), stmt => (...bind: TBind) => { stmt.run(...bind); });
// #endregion
// #region db statements
const dbAdapt = {
    get: (id: ItemId, type: string, status: string, name: string, description: string) => ({ id, status, type, name, description }),
    summ: (id: ItemId, type: string, status: string, name: string) => ({ id, status, type, name }),
    link: (rel: string, id: ItemId, status: string, type: string, name: string): [string, ItemSummary] => [rel, { id, status, type, name }]
};
const db = {
    get: Q<[ItemId, string, string, string, string], [ItemId], Item>(dbAdapt.get, `SELECT id, ${issueFields.join(", ")} FROM item WHERE id = ?`),
    fwd: q<[string, ItemId, string, string, string], [ItemId], [string, ItemSummary]>(dbAdapt.link,
        "SELECT link.type AS rel, item.id, item.status, item.type, item.name FROM link JOIN item ON item.id = link.b WHERE link.a = ?"),
    bwd: q<[string, ItemId, string, string, string], [ItemId], [string, ItemSummary]>(dbAdapt.link,
        `SELECT linktype.back AS rel, item.id, item.status, item.type, item.name FROM link
            JOIN linktype ON linktype.type = link.type JOIN item ON item.id = link.a WHERE link.b = ?`),
    cItem: Q<[ItemId], [string, string, string, string], ItemId>((id) => id, "INSERT INTO item (type, status, name, description) VALUES (?, ?, ?, ?) RETURNING id"),
    cLink: E<[string, ItemId, ItemId]>("INSERT INTO link (type, a, b) VALUES (?, ?, ?)"),
    rLink: E<[string, ItemId, ItemId]>("DELETE FROM link WHERE type = ? AND a = ? AND b = ?"),
    itemsLinked: (back: boolean, without: boolean) => q<[ItemId, string, string, string], [string, string], ItemSummary>(dbAdapt.summ,
        `SELECT id, type, status, name FROM item WHERE status = ? AND ${without ? "NOT" : ""} EXISTS(
            SELECT 1 FROM link JOIN item linked ON linked.id = link.${back ? "a": "b"} WHERE link.type = ? AND ${back ? "b": "a"} = item.id AND linked.status != 'closed')`),
} as const;
// #endregion
// #region db
const statuses = ["open", "claimed", "closed"]; // TODO: allow config-ing this, un-hardcode defaults
const itemTypes = q<[string], [], string>((t) => t, `SELECT type FROM itemtype`)();
const linkTypes = pipe(q<[string, string], []>((f,b) => [f,b], `SELECT type, back FROM linktype`)(), lt => {
    const symm = new Set(lt.filter(([f,b]) => f === b).map(([f]) => f));
    const back = Object.fromEntries(lt.filter(([f]) => !symm.has(f)).map(([f,b]) => [b,f]));
    return { raw: lt, set: new Set(lt.map(([f,b]) => [f,b]).flat()), symm, back };
});
const normalizeLink = (t: string, a: ItemId, b: ItemId): [string, ItemId, ItemId] =>
    t in linkTypes.back ? [linkTypes.back[t], b, a] : linkTypes.symm.has(t) ? a < b ? [t, a, b] : [t, b, a] : [t, a, b];
const rels = (id: ItemId) => pipe([...db.fwd(id), ...db.bwd(id)], raw => tap<Links>({}, res => {
    for (const [rel,r] of raw) (res[rel] ??= []).push(r);
}));
const show = (id: ItemId): ItemLinks | undefined => pipe(db.get(id), res => res && ({ ...res, links: rels(id) }));
// #endregion
// #region validator
const runValidator = async (id: ItemId): Promise<boolean> => {
    if (Deno.env.has("WQ_OVERRIDE_VALIDATION")) return Deno.env.get("WQ_OVERRIDE_VALIDATION") === "1";
    const p = pipe(config.validator as string[], ([command, ...commandArgs]) => new Deno.Command(command,
            { args: commandArgs, cwd: wqd, stdin: "piped", stdout: "piped", stderr: "inherit" }).spawn());
    const w = p.stdin.getWriter();
    await w.write(new TextEncoder().encode(JSON.stringify(show(id))));
    w.releaseLock(); await p.stdin.close();
    return (await p.output()).success;
};
const validate = async (f: () => ItemId[]): Promise<ItemId[]> => {
    try {
        conn.exec("BEGIN");
        const ids = f();
        for (const id of ids)
            if (!(await runValidator(id))) { conn.exec("ROLLBACK"); Deno.exit(1); }
        conn.exec("COMMIT");
        return ids;
    } catch (e) { conn.exec("ROLLBACK"); throw e; };
};
// #endregion
// #region arg parsing
const config = JSON.parse(await Deno.readTextFile(resolve(wqd, "config.json")));
const defaults = ("defaults" in config && cmd in config.defaults) ? config.defaults[cmd] : {};
const args = parseArgs(Deno.args, {
    boolean: ["human"], string: [...issueFields, "link-type"], alias: { "h": "human" }, collect: [...linkTypes.set] as ["blocks", "blocked-by"],
    default: defaults as { "link-type": "blocked-by" },
});
const itemIdsIn = (xs: (number | string)[]): ItemId[] => {
    xs.filter(it => typeof it !== "number").forEach(it => console.error(`warn: ${it} is not a valid item id`));
    return tap(xs.filter(it => typeof it === "number"), ids => ids.length || console.error(`warn: no valid item id arguments`));
};
const existingItemIdsIn = (xs: (number | string)[]): ItemId[] => tap(itemIdsIn(xs), ids => ids.forEach(id => db.get(id) || err(`item ${id} does not exist`)));
const definedIn = <T>(ts: readonly (T | undefined)[]): T[] => ts.filter(t => t !== undefined);
const definedOf = <K extends keyof T, T>(ks: readonly K[], t: T): K[] => ks.filter(k => t[k] !== undefined);
const assertNonNull = <T>(t: T, msg: string): NonNullable<T> => { if (t === undefined) err(msg, true); return t!; }
const requireArg = <T extends keyof typeof args>(arg: T) => assertNonNull(args[arg], `argument ${arg} is required`);
const linkArgs = (as: ItemId[]) => pipe(definedOf([...linkTypes.set], args).flatMap(t => itemIdsIn(args[t] as string[]).map<[string,ItemId]>(b => [t,b])),
    tbs => as.flatMap(a => tbs.map(([t,b]) => normalizeLink(t,a,b))));
const requireLinkArgs = (as: ItemId[]) => tap(linkArgs(as), r => { if (r.length === 0) err("no link arguments", true); });
// #endregion
// #region main
const indent = (s: string) => "    " + s.replaceAll("\n", "\n    ");
const humanizeLinks = (l: Links) => Object.entries(l).flatMap(([t,os]) => os.map(o => t + ": " + humanize(o))).join("\n");
const humanize = (o: Output): string => Array.isArray(o) ? o.map(humanize).join("\n")
    : `#${o.id} ${o.name} (${o.status} ${o.type})${"description" in o ? "\n\n" + indent(o.description + (Object.keys(o.links).length ? "\n\n" + humanizeLinks(o.links) : "")) + "\n" : ""}`;
const O = (o: Output) => console.log(args.human ? humanize(o) : JSON.stringify(o));
const cmds: Record<string, () => void | Promise<void>> = {
    "prime": () => pipe<Record<string, string>, Promise<void>>({
            itemTypes: itemTypes.join("|"), statuses: statuses.join("|"), wqSrc: resolve(src, "wq"),
            linkArgs: linkTypes.raw.map(([a,b]) => `--${a} <id>` + (a !== b ? ` --${b} <id>` : "")).join("  "),
        }, parts => Deno.readTextFile(resolve(src, "PRIMER.md")).then(it => it.replaceAll(/\{([^\}]+)\}/g, (_,k) => parts[k])).then(x => console.log(x))),
    "show": () => O(itemIdsIn(args._).map(id => show(id) || console.error(`warn: item ${id} does not exist`)).filter<ItemLinks>(it => it !== undefined)),
    "create": () => validate(() => pipe(db.cItem(requireArg("type"), requireArg("status"), requireArg("name"), requireArg("description"))!,
        id => tap([id], as => linkArgs(as).forEach(l => db.cLink(...l))))).then(([id]) => O(show(id)!)),
    "update": () => pipe(pipe(tap(definedOf(issueFields, args), fields => fields.length || err("no update fields", true)), fields =>
        pipe(fields.map(k => args[k]), vals => (id: ItemId) => E(`UPDATE item SET ${fields.map(f => `${f} = ?`).join(",")} WHERE id = ?`)(...vals, id))),
            doUpdate => validate(() => existingItemIdsIn(args._).map(id => tap(id, doUpdate))).then(ids => O(definedIn(ids.map(show))))),
    "link": () => validate(() => tap(existingItemIdsIn(args._), as => requireLinkArgs(as).forEach(l => db.cLink(...l)))).then(ids => O(definedIn(ids.map(show)))),
    "unlink": () => validate(() => tap(existingItemIdsIn(args._), as => requireLinkArgs(as).forEach(l => db.rLink(...l)))).then(ids => O(definedIn(ids.map(show)))),
    "list": () => {
        const arr = (arg: string | undefined, field: string) => pipe(arg?.split(","), it => [`${field} IN (${it.map(_ => "?")})`, it]);
        const kwd = (arg: string | undefined, field: string) => pipe(arg, it => [`${field} LIKE ?`, [`%${it}%`]]);
        const c = definedIn([ arr(args["type"],"type"), arr(args["status"],"status"), kwd(args["name"],"name"), kwd(args["description"],"description") ] as ([string,string[]] | undefined)[]);
        O(q(dbAdapt.summ, `SELECT id, type, status, name FROM item ${c.length ? "WHERE " : ""}${c.map(([c]) => c).join(" AND ")}`)(...c.flatMap(([_,v]) => v)));
    },
    "ready": () => pipe(args["link-type"], t => pipe(t in linkTypes.back, back => O(db.itemsLinked(back, true)(requireArg("status"), back ? linkTypes.back[t] : t)))),
    "blocked": () => pipe(args["link-type"], t => pipe(t in linkTypes.back, back => O(db.itemsLinked(back, false)(requireArg("status"), back ? linkTypes.back[t] : t)))),
    "claim": () => { args.status = "claimed"; return cmds["update"](); }, "close": () => { args.status = "closed"; return cmds["update"](); },
};
if (cmd in cmds) await cmds[cmd](); else help();
// #endregion
