#!/usr/bin/env -S deno run -A
// #region imports
import { Database, RestBindParameters } from "@db/sqlite";
import { resolve } from "@std/path";
import { ensureDir, exists, copy } from "@std/fs";
import { promises as fs } from "node:fs";
import { parseArgs } from "@std/cli/parse-args";
// #endregion
// #region sanity check
const tap = <T>(t: T, f: (t: T) => void) => { f(t); return t; };
const pipe = <T, R>(t: T, f: (t: T) => R) => { return f(t); };
const ensureAllExist = async (dir: string, fs: string[]) => {
    for (const f of fs)
        if (!await exists(resolve(dir, f)))
            throw new Error(`expected file ${resolve(dir, f)} missing`);
};
const src = import.meta.dirname;
if (!src) throw new Error(`failed to get import.meta.dirname`);
await ensureAllExist(src, ["PRIMER.md", "usage.txt", "validator.default", "schema.sql"]);
// #endregion
// #region help, init (commands that don't open an existing db)
const cmd = Deno.args.shift();
const help = async () => console.error(await fs.readFile(resolve(src, "usage.txt"), { encoding: "utf-8" }));
if (typeof cmd !== "string" || cmd === "help") { await help(); Deno.exit(); } else if (cmd === "init") {
    const wqd = resolve(Deno.cwd(), ".wq") 
    ensureDir(wqd);
    const db = new Database(resolve(wqd, "db"));
    db.exec("pragma journal_mode = WAL;");
    db.exec(await fs.readFile(resolve(src, "schema.sql"), { encoding: "utf-8" }));
    copy(resolve(src, "validator.default"), resolve(wqd, "validator"));
    fs.chmod("775", resolve(wqd, "validator"));
    console.error(`init: created ${wqd}`);
    Deno.exit();
}
// #endregion
// #region find .wq
const wqd = await (async () => {
    let d = Deno.cwd(); let p = d;
    do {
        const r = resolve(d = p, ".wq");
        if (await exists(r)) return r;
    } while (d !== (p = resolve(d, "..")));
    throw new Error("coulnd't find .wq");
})();
ensureAllExist(wqd, ["db", "validator"]);
// #endregion
// #region types
type ItemSummary = { id: number, state: string, type: string, name: string, rel?: string };
type Item = ItemSummary & { description: string };
type Links = Record<string, ItemSummary[]>;
type ItemLinks = Item & { links: Links };
// #endregion
// #region db
const conn = new Database(resolve(wqd, "db")); conn.exec("pragma foreign_keys = ON");
const q = <TCols extends unknown[], TBind extends RestBindParameters, TRet> (query: string, f: (t: TCols) => TRet) =>
    pipe(conn.prepare(query), stmt => (...bind: TBind) => stmt.values<TCols>(...bind).map(f));
const Q = <TCols extends unknown[], TBind extends RestBindParameters, TRet> (query: string, f: (t: TCols) => TRet) =>
    pipe(conn.prepare(query), stmt => (...bind: TBind) => pipe(stmt.value<TCols>(...bind), ret => ret ? f(ret) : undefined));
const db = {
    get: Q<[number, string, string, string, string], [number], Item>(
        "SELECT id, state, type, name, description FROM item WHERE id = ?",
        ([id, state, type, name, description]) => ({ id, state, type, name, description })),
    fwd: q<[string, number, string, string, string], [number], ItemSummary>(
        "SELECT link.type AS rel, item.id, item.state, item.type, item.name FROM link JOIN item ON item.id = link.b WHERE link.a = ?",
        ([rel, id, state, type, name]) => ({ rel, id, state, type, name })),
    bwd: q<[string, number, string, string, string], [number], ItemSummary>(
        `SELECT linktype.back AS rel, item.id, item.state, item.type, item.name FROM link
            JOIN linktype ON linktype.type = link.type JOIN item ON item.id = link.a WHERE link.b = ?`,
        ([rel, id, state, type, name]) => ({ rel, id, state, type, name })),
} as const;
const statuses = ["open","claimed","closed"]; // TODO: maybe also allow config-ing this?
const itemTypes = q<[string], [], string>(`SELECT type FROM itemtype`, ([t]) => t)();
const linkTypes = q<[string, string], [], [string, string]>(`SELECT type, back FROM linktype`, x => x)();

const rels = (id: number) => pipe([...db.fwd(id), ...db.bwd(id)], raw => tap<Links>({}, res => {
    for (const r of raw) (res[r.rel!] ??= []).push(tap(r, () => { delete r.rel; }))
}));
const show = (id: number): ItemLinks | undefined => pipe(db.get(id), res => res && ({ ...res, links: rels(id) }));

// #endregion
// #region main
const args = parseArgs(Deno.args, {
    boolean: ["human", "claim"], string: ["name", "description", "status", "type"], alias: { "h": "human" },
    collect: linkTypes.flat() as ["blocks", "blocked-by"], // lie to the type system or it thinks everything is arrays
});
const idArgs = () => {
    args._.filter(it => typeof it !== "number").forEach(it => console.error(`err: ${it} is not a valid item id`));
    return args._.filter(it => typeof it === "number");
}
const J = (x: unknown) => console.log(JSON.stringify(x)); // TODO: --human
const cmds = {
    "prime": async () => {
        const parts: Record<string, string> = {
            itemTypes: itemTypes.join("|"),
            statuses: statuses.join("|"),
            linkArgs: linkTypes.map(([a,b]) => `--${a} <id> --${b} <id>`).join("  ")
        };
        console.log(await fs.readFile(resolve(src, "usage.txt"), { encoding: "utf-8" })
            .then(it => it.replaceAll(/\{([^\}]+)\}/, (_,k) => parts[k])));
    },
    "show": () => J(idArgs().map(it => show(it) || console.error(`warn: item ${it} does not exist`)).filter(it => it)),
    "create": () => { console.error("not yet implemented") },
    "update": () => { console.error("not yet implemented") },
    "list": () => { console.error("not yet implemented") },
    "ready": () => { console.error("not yet implemented") },
    "blocked": () => { console.error("not yet implemented") },
    "claim": () => { console.error("not yet implemented") },
    "unclaim": () => { console.error("not yet implemented") },
    "close": () => { console.error("not yet implemented") },
};
if (cmd in cmds) await cmds[cmd as keyof typeof cmds](); else await help();
// #endregion
